baseURL = "https://galleriesdeluxe.netlify.app/"

[author]
    name  = "Bjørn Erik Pedersen"
    email = "bjorn.erik.pedersen@gmail.com"

[taxonomies]
    category = 'categories'

[caches]
    [caches.images]
        dir    = ':cacheDir/galleriesdeluxe'
        maxAge = "4320h"                     # 6 months.

[params]
    description = "A Hugo gallery website"

    [params.gallerydeluxe]
        shuffle     = false
        reverse     = true
        enable_exif = false

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"

    [[module.imports]]
        path = "github.com/bep/galleriesdeluxe"
