baseURL = "https://galleriesdeluxe.netlify.app/"

<<<<<<< HEAD
[author]
    name  = "Griffin Wirth"
    email = "griffiniwirth@gmail.com"

=======
>>>>>>> ef635d564213e7841a87c8e5d1fafcb466c9c2d2
[taxonomies]
    category = 'categories'

[caches]
    [caches.images]
        dir    = ':cacheDir/galleriesdeluxe'
        maxAge = "4320h"                     # 6 months.

[params]
    [params.author]
        name        = "Bjørn Erik Pedersen"
        email       = "bjorn.erik.pedersen@gmail.com"
        description = "A Hugo gallery website"

    [params.galleriesdeluxe]
        # One of dartsass or libsass.
        sass_transpiler = "dartsass"
        [params.galleriesdeluxe.sassvars]
            color_background = "#1d1e2c"

[params.gallerydeluxe]
    shuffle     = false
    reverse     = true
    enable_exif = false

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"

    [[module.imports]]
        path = "github.com/bep/galleriesdeluxe"
